---
title: "Untitled"
author: "Zichun Liu"
date: "2/28/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = normalizePath("~/Documents/BU/2017SPRING/MA676/GSS_Data_Challenge/"))
```


#explore
```{r}
fmli151x = read.csv(file = "~/Documents/BU/2017SPRING/MA676/GSS_Data_Challenge//DATA/intrvw15/intrvw15/fmli151x.csv",header = T,stringsAsFactors = F)
```

```{r}
table(fmli151x$QINTRVMO)
##   2    3 
##2109 2094 
table(fmli151x$QINTRVYR)
##2015 
##4203 
```

```{r}
require(stringi)
tmp = stri_sub(fmli151x$NEWID, from = -1, to = -1)
table(tmp)
##interview number
##   1    2    3    4    5 
## 392 1027 1055 1055  674 
```


```{r}
table(fmli151x$HH_CU_Q)
#table(fmli151x$HH_CU_Q_)
```

```{r}
(fmli151x$HHID)
length(unique(fmli151x$HHID))
table(fmli151x$HHID)
```

```{r}
cuid = as.integer(stri_sub(fmli151x$NEWID, from = 1, to = -2))
cuid1 = fmli151x$CUID
identical(cuid,cuid1)
```

```{r}
identical(fmli151x$INTERI,as.integer(tmp))
```


```{r}
table(fmli151x$AS_COMP1)



table(fmli151x$AS_COMP2)

table(fmli151x$AS_COMP2[which(fmli151x$AS_COMP1==0)])
```

```{r}
table(fmli151x$EARNCOMP)
```
```{r}
table(fmli151x$FAM_SIZE)
#table(fmli151x$FAM__IZE)
```
```{r}
fmli151x$INC_RANK
fmli151x$ERANKH
#ERANKH vs ERANKHM

head(fmli151x$WTREP02)

```




```{r}
car1 = read.csv("../DATA/intrvw15/expn15/ovb15.csv",header = T, stringsAsFactors = F)
car2 = read.csv("../DATA/intrvw15/expn15/ovc15.csv",header = T, stringsAsFactors = F)
```

